"""Initial migration.

Revision ID: 06e0dc263a65
Revises: 
Create Date: 2025-01-28 11:08:50.511464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e0dc263a65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense_manager')
    op.drop_table('expense')
    with op.batch_alter_table('income_expense_manager', schema=None) as batch_op:
        batch_op.alter_column('from_bank',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('hbank', 'ibank', 'pbank', name='bank_enum'),
               existing_nullable=False)
        batch_op.alter_column('to_bank',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('hbank', 'ibank', 'pbank', name='bank_enum'),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('income', 'expense', 'saving', 'investment', 'transfer', name='category_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_expense_manager', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.Enum('income', 'expense', 'saving', 'investment', 'transfer', name='category_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('to_bank',
               existing_type=sa.Enum('hbank', 'ibank', 'pbank', name='bank_enum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('from_bank',
               existing_type=sa.Enum('hbank', 'ibank', 'pbank', name='bank_enum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    op.create_table('expense',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('from_bank', sa.VARCHAR(length=10), nullable=False),
    sa.Column('to_bank', sa.VARCHAR(length=10), nullable=True),
    sa.Column('category', sa.VARCHAR(length=20), nullable=False),
    sa.Column('sub_category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.VARCHAR(length=100), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_manager',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('from_bank', sa.VARCHAR(length=10), nullable=False),
    sa.Column('to_bank', sa.VARCHAR(length=10), nullable=True),
    sa.Column('category', sa.VARCHAR(length=20), nullable=False),
    sa.Column('sub_category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.VARCHAR(length=100), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
