"""Allow NULL in from_bank

Revision ID: 31b6f46f5707
Revises: 06e0dc263a65
Create Date: 2025-01-29 15:08:20.613533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31b6f46f5707'
down_revision = '06e0dc263a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_expense_manager', schema=None) as batch_op:
        batch_op.alter_column('from_bank',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               nullable=True)
        batch_op.alter_column('to_bank',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_expense_manager', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('to_bank',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
        batch_op.alter_column('from_bank',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               nullable=False)

    # ### end Alembic commands ###
