"""added status

Revision ID: 6c17a1d7d338
Revises: cee2a72f59d7
Create Date: 2022-02-16 11:53:45.891082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c17a1d7d338'
down_revision = 'cee2a72f59d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('stat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stat_id'], ['games_played.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_games')
    # ### end Alembic commands ###
